id: P3F0C6CCC
initial_creation_type: ocr
source_metadata:
  volumes:
    d33c890b565641699f1de72fc744f647:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: འཕགས་པ་རྗེ་བཙུན་འཇམ་དཔལ་གྱི་དོན་དམ་པའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
